version: '3'

services:
    sgx:
        build: .
        ports:
            - '5000:5000'
        environment:
            - HOGE
        command: make develop
        volumes:
            - .:/root
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp=unconfined
